version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql
    hostname: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ventas

    volumes:
      - ./src/main/sql/create.sql:/docker-entrypoint-initdb.d/init.sql

    ports:
      - "3306:3306"
  app:
    image: maven:3.8.4-openjdk-17
    container_name: springboot-app
    restart: always
    working_dir: /app
    volumes:
      - .:/app 
    command: mvn spring-boot:run
    ports:
      - "8080:8080" 
    depends_on:
      - db 